{% set name = "compas_occ" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/compas-dev/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 72d430d56512ab11d7077eabdc01a69b4e9e2c1962511c2cb02764b0f317aaa6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - compas
    - pythonocc-core

test:
  requires:
    - python {{ python_min }}
  imports:
    - compas_occ

about:
  home: http://github.com/compas-dev/compas_occ
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: COMPAS wrappers for OCC
  description: |
    COMPAS OCC is a wrapper for the 3D geometry kernel of Open Cascade
    based on the Python bindings in pythonocc-core
    and with an API similar to the one of RhinoCommon.
  doc_url: http://compas.dev/compas_occ
  dev_url: https://github.com/compas-dev/compas_occ

extra:
  recipe-maintainers:
    - tomvanmele
    - licini
