{% set name = "compas_occ" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6a7851ab0212e8eae7b1a40db32a99d42b8a83e687db69fe6df718b72cb78257

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - compas
    - pythonocc-core

test:
  imports:
    - compas_occ

about:
  home: http://github.com/compas-dev/compas_occ
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: COMPAS wrappers for OCC
  description: |
    COMPAS OCC is a wrapper for the 3D geometry kernel of Open Cascade
    based on the Python bindings in pythonocc-core
    and with an API similar to the one of RhinoCommon.
  doc_url: http://compas.dev/compas_occ
  dev_url: https://github.com/compas-dev/compas_occ

extra:
  recipe-maintainers:
    - tomvanmele
    - licini
